kind: project
metadata:
  name: katacoda
spec:
  functions:
  # main function example
  - url: gen_iris.py
    name: gen-iris
    image: mlrun/mlrun
  # function handler + auto_log example
  - url: trainer.py
    name: trainer
    handler: train
    image: mlrun/mlrun
